source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'alamofire-swiftyjson' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.3'
  pod 'SwiftyJSON', '~> 2.3'

end
